language: go

go:
  - 1.8
  - master

script:
  - GOARCH=amd64 GOOS=linux go build main.go -o bin/gecho-linux-amd64
  - GOARCH=amd64 GOOS=darwin go build main.go -o bin/gecho-darwin-amd64
  - GOARCH=amd64 GOOS=windows go build main.go -o bin/gecho-windows-amd64
