language: go
go:
- 1.8
script:
- GOARCH=amd64 GOOS=linux go build -o bin/gecho-linux-amd64
- GOARCH=amd64 GOOS=darwin go build -o bin/gecho-darwin-amd64
- GOARCH=amd64 GOOS=windows go build -o bin/gecho-windows-amd64

deploy:
  provider: releases
  api_key:
      secure: YGlhhnSlvk+Xhg7OO5K+kkjfRrlzpW+B3vNj6o9XgJk86xIX9rd7Swrlok2Urz6PQHHZtKCy1aHmVwyVoFi3tu8GhAnHjyzxELHOT24SGWM2zhjbmnM1kQ6hsXMmKBwGCcLBZ3AdZUMkUUy5cafJ+QfhalvqxWt/9hMD8nV547zGuMLc9IG/ONv4M31pPxeZnHiq35dgVciKgolb/8gNh/jdEUFgMb6Lnbvj/rC/uyQa/iBHDy9Knk2zccW1dgXgl0wzaO1fPSVvZKqrW/gV8JtQjsG8zlulixCsSL429vCl2QuHiVxCy1eLz6G6LqqNUSea/4k6YwSWAgGBbem/B4PUDhJhuwFiRyF/b+q16e3i2HBbxk2urog1yJWMsE7lyi85XaoShygllk9MgzxHFPyXCrHLbHizQjXpIP5cBgkYssmoiogD+qYt17itnnX2Bj3wEmwfdRQwkFtTnfS1m2BrJ1FYrB9fZKSb1c7uSne5uBQP7dL7Zjml20EgyIx6m8Pvhb8So+HYsl8RToSlzzlK92kZyIRjIpCF/sFOxP1s0RQbPCzlYy+Vzb3uqDSsA/6wUAogcOzL93fY37l0SxqlpDs/oM/VzUZXC9tIh9JSrSUYp+XWsOp7zTqbLV4NcgCLSeopmPLIZ3JcXAoo4qjqVMAPBDXQ2QtDQt4EENk=
  file:
    - "bin/gecho-linux-amd64"
    - "bin/gecho-darwin-amd64"
    - "bin/gecho-windows-amd64"
  skip_cleanup: true
  on:
    tags: true
